<a href="https://colab.research.google.com/github/Gaukhar-ai/working-in-pairs/blob/master/Copy_of_Day_54_Lecture_2_SOM_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install minisom

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# !pip install minisom
from minisom import MiniSom

import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

%matplotlib inline

In [3]:
def som_pie_grid(som, data, labels):
  """Helper to create piechart grid viz
  
  Example: https://raw.githubusercontent.com/JustGlowing/minisom/master/examples/resulting_images/som_iris_pies.png

  :param som: fitted MiniSom instance
  :param data: the data the MiniSom was fit to
  :param labels: an array of labels to use for coloring visual
  """
  labels_map = som.labels_map(data, labels)
  label_names = np.unique(labels)

  plt.figure(figsize=(70, 70))
  the_grid = GridSpec(70, 70)
  for position in labels_map.keys():
      label_fracs = [labels_map[position][lab] for lab in label_names]
      plt.subplot(the_grid[position[1] - 12, position[0]], aspect=1)
      patches, texts = plt.pie(label_fracs)

  plt.show()

  # Cheating way to align legend, create a separate figure just 
  # for legend.  Will have superfluous whitespace below
  plt.legend(patches, label_names, loc='upper left', ncol=5)
  plt.axis('off')
  plt.show()

* Read in the data from `data_url`
* Drop all NAs
* Filter based on the `'Pos'` column to where only have the positions `['C', 'PG', 'SG']` remain
* Drop all non-numeric columns
* Scale the data

In [4]:
df_orig = pd.read_csv("https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Data%20Sets%20Clustering/nba_player_seasons.csv")
df_orig.head()

   Seas        Player Pos  Age   Tm   G  GS  ...  TRB  AST  STL  BLK  TOV   PF   PTS
0  2019  √Ålex Abrines  SG   25  OKC  31   2  ...  1.5  0.6  0.5  0.2  0.5  1.7   5.3
1  2019    Quincy Acy  PF   28  PHO  10   0  ...  2.5  0.8  0.1  0.4  0.4  2.4   1.7
2  2019  Jaylen Adams  PG   22  ATL  34   1  ...  1.8  1.9  0.4  0.1  0.8  1.3   3.2
3  2019  Steven Adams   C   25  OKC  80  80  ...  9.5  1.6  1.5  1.0  1.7  2.6  13.9
4  2019   Bam Adebayo   C   21  MIA  82  28  ...  7.3  2.2  0.9  0.8  1.5  2.5   8.9

[5 rows x 30 columns]

In [5]:
df = df_orig.copy()

In [6]:
df.isna().sum()
df = df.dropna()

In [7]:
df.isna().sum()

Seas      0
Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

In [8]:
df = df[df['Pos'].isin(['C', 'PG', 'SG'])]
df.head()

   Seas                  Player Pos  Age   Tm  ...  STL  BLK  TOV   PF   PTS
0  2019            √Ålex Abrines  SG   25  OKC  ...  0.5  0.2  0.5  1.7   5.3
2  2019            Jaylen Adams  PG   22  ATL  ...  0.4  0.1  0.8  1.3   3.2
3  2019            Steven Adams   C   25  OKC  ...  1.5  1.0  1.7  2.6  13.9
4  2019             Bam Adebayo   C   21  MIA  ...  0.9  0.8  1.5  2.5   8.9
6  2019  DeVaughn Akoon-Purcell  SG   25  DEN  ...  0.3  0.0  0.3  0.6   1.0

[5 rows x 30 columns]

In [9]:
df.dtypes
df = df.drop(columns=['Tm', 'Player'])

* Fit a `MiniSom` instance to the scaled data
  * Choose your own grid size
  * Set a `random_seed` to have reproducible results
  * Initialize the `MiniSom` weight vectors using `.pca_weights_init()` or `.random_weights_init()`
  * Train the model using `.train_random()` or `.train_batch()`

In [10]:
X = df.drop(columns='Pos')
y = df['Pos']

In [12]:
scale = StandardScaler()
scaled = scale.fit_transform(X)

In [13]:
som =

      Seas  Age   G  GS    MP   FG   FGA  ...  TRB  AST  STL  BLK  TOV   PF   PTS
0     2019   25  31   2  19.0  1.8   5.1  ...  1.5  0.6  0.5  0.2  0.5  1.7   5.3
2     2019   22  34   1  12.6  1.1   3.2  ...  1.8  1.9  0.4  0.1  0.8  1.3   3.2
3     2019   25  80  80  33.4  6.0  10.1  ...  9.5  1.6  1.5  1.0  1.7  2.6  13.9
4     2019   21  82  28  23.3  3.4   5.9  ...  7.3  2.2  0.9  0.8  1.5  2.5   8.9
6     2019   25   7   0   3.1  0.4   1.4  ...  0.6  0.9  0.3  0.0  0.3  0.6   1.0
...    ...  ...  ..  ..   ...  ...   ...  ...  ...  ...  ...  ...  ...  ...   ...
2134  2016   22   8   3  18.0  2.8   8.1  ...  2.6  2.5  0.4  0.0  3.6  1.4   8.4
2135  2016   20  29   0   6.9  0.4   1.2  ...  0.9  0.3  0.2  0.0  0.2  0.6   1.0
2136  2016   23  41   0   9.4  1.5   4.1  ...  1.2  1.6  0.4  0.0  0.8  0.7   3.8
2137  2016   30  54   2  19.1  2.3   6.9  ...  1.8  0.6  0.4  0.1  0.6  0.9   7.3
2139  2016   23  73  60  24.3  3.2   6.0  ...  6.2  1.0  0.8  0.9  0.9  2.8   8.7

[1154 rows x 27 columns]

* Use the helper function defined at the top of the notebook to plot the SOM's fit
  * Use the players' positions (the `'Pos'` column) as the labels in the viz
  * Experiment with the SOM's grid size, initialization method, and training method.  Decide a 'good' fit using this visual as guidance.

In [ ]:
som.

* Perform dimension reduction (to 2d) with another method (perhaps `PCA` or `TSNE`).
* Create a scatter plot of the results of this dimension reduction and color the scatter plot by the players' positions (the `'Pos'` column).
  * How do these results compare to that of the SOM? What are the pros and cons of the different approaches you took in this notebook?